// Sample data used when VITE_API_URL is not set (real teams/players from the baseline Sheet; games and article are made up).
import type { Article, Game, Meta, Player, Row, Team } from './types';

export const sampleMeta: Meta = { currentSeason: 1, sheetName: 'Sample data' };
export const sampleTeams = [
{
"TeamIndex (save ID)": 2,
"City": "Buffalo",
"Nickname (click)": "Bills",
"Abbr": "BUF",
"Conference": "AFC",
"Division": "East",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 11,
"City": "Miami",
"Nickname (click)": "Dolphins",
"Abbr": "MIA",
"Conference": "AFC",
"Division": "East",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 21,
"City": "New England",
"Nickname (click)": "Patriots",
"Abbr": "NE",
"Conference": "AFC",
"Division": "East",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 17,
"City": "New York",
"Nickname (click)": "Jets",
"Abbr": "NYJ",
"Conference": "AFC",
"Division": "East",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 24,
"City": "Baltimore",
"Nickname (click)": "Ravens",
"Abbr": "BAL",
"Conference": "AFC",
"Division": "North",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 1,
"City": "Cincinnati",
"Nickname (click)": "Bengals",
"Abbr": "CIN",
"Conference": "AFC",
"Division": "North",
"Head Coach": "Christian",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 4,
"City": "Cleveland",
"Nickname (click)": "Browns",
"Abbr": "CLE",
"Conference": "AFC",
"Division": "North",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 28,
"City": "Pittsburgh",
"Nickname (click)": "Steelers",
"Abbr": "PIT",
"Conference": "AFC",
"Division": "North",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 31,
"City": "Houston",
"Nickname (click)": "Texans",
"Abbr": "HOU",
"Conference": "AFC",
"Division": "South",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 9,
"City": "Indianapolis",
"Nickname (click)": "Colts",
"Abbr": "IND",
"Conference": "AFC",
"Division": "South",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 16,
"City": "Jacksonville",
"Nickname (click)": "Jaguars",
"Abbr": "JAX",
"Conference": "AFC",
"Division": "South",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 29,
"City": "Tennessee",
"Nickname (click)": "Titans",
"Abbr": "TEN",
"Conference": "AFC",
"Division": "South",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 3,
"City": "Denver",
"Nickname (click)": "Broncos",
"Abbr": "DEN",
"Conference": "AFC",
"Division": "West",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 8,
"City": "Kansas City",
"Nickname (click)": "Chiefs",
"Abbr": "KC",
"Conference": "AFC",
"Division": "West",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 22,
"City": "Las Vegas",
"Nickname (click)": "Raiders",
"Abbr": "LV",
"Conference": "AFC",
"Division": "West",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 7,
"City": "Los Angeles",
"Nickname (click)": "Chargers",
"Abbr": "LAC",
"Conference": "AFC",
"Division": "West",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 10,
"City": "Dallas",
"Nickname (click)": "Cowboys",
"Abbr": "DAL",
"Conference": "NFC",
"Division": "East",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 15,
"City": "New York",
"Nickname (click)": "Giants",
"Abbr": "NYG",
"Conference": "NFC",
"Division": "East",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 12,
"City": "Philadelphia",
"Nickname (click)": "Eagles",
"Abbr": "PHI",
"Conference": "NFC",
"Division": "East",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 25,
"City": "Washington",
"Nickname (click)": "Commanders",
"Abbr": "WAS",
"Conference": "NFC",
"Division": "East",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 0,
"City": "Chicago",
"Nickname (click)": "Bears",
"Abbr": "CHI",
"Conference": "NFC",
"Division": "North",
"Head Coach": "Wes",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 18,
"City": "Detroit",
"Nickname (click)": "Lions",
"Abbr": "DET",
"Conference": "NFC",
"Division": "North",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 19,
"City": "Green Bay",
"Nickname (click)": "Packers",
"Abbr": "GB",
"Conference": "NFC",
"Division": "North",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 30,
"City": "Minnesota",
"Nickname (click)": "Vikings",
"Abbr": "MIN",
"Conference": "NFC",
"Division": "North",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 13,
"City": "Atlanta",
"Nickname (click)": "Falcons",
"Abbr": "ATL",
"Conference": "NFC",
"Division": "South",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 20,
"City": "Carolina",
"Nickname (click)": "Panthers",
"Abbr": "CAR",
"Conference": "NFC",
"Division": "South",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 26,
"City": "New Orleans",
"Nickname (click)": "Saints",
"Abbr": "NO",
"Conference": "NFC",
"Division": "South",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 5,
"City": "Tampa Bay",
"Nickname (click)": "Buccaneers",
"Abbr": "TB",
"Conference": "NFC",
"Division": "South",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 6,
"City": "Arizona",
"Nickname (click)": "Cardinals",
"Abbr": "ARI",
"Conference": "NFC",
"Division": "West",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 23,
"City": "Los Angeles",
"Nickname (click)": "Rams",
"Abbr": "LAR",
"Conference": "NFC",
"Division": "West",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 14,
"City": "San Francisco",
"Nickname (click)": "49ers",
"Abbr": "SF",
"Conference": "NFC",
"Division": "West",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
},
{
"TeamIndex (save ID)": 27,
"City": "Seattle",
"Nickname (click)": "Seahawks",
"Abbr": "SEA",
"Conference": "NFC",
"Division": "West",
"Head Coach": "CPU",
"Record": "0-0",
"Super Bowl Wins": 0
}
] as unknown as Team[];
export const samplePlayers = [
{
"PlayerID": "P0001",
"First Name": "Joe",
"Last Name": "Thuney",
"Position": "LG",
"Age": 33,
"Overall": 96,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 62,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0002",
"First Name": "Caleb",
"Last Name": "Williams",
"Position": "QB",
"Age": 24,
"Overall": 91,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 18,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0003",
"First Name": "Jaylon",
"Last Name": "Johnson",
"Position": "CB",
"Age": 27,
"Overall": 90,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 1,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0004",
"First Name": "Darnell",
"Last Name": "Wright",
"Position": "RT",
"Age": 25,
"Overall": 87,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 58,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0005",
"First Name": "Devin",
"Last Name": "Bush",
"Position": "MLB",
"Age": 28,
"Overall": 86,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 12,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0006",
"First Name": "D'Andre",
"Last Name": "Swift",
"Position": "HB",
"Age": 27,
"Overall": 86,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 4,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0007",
"First Name": "Kyler",
"Last Name": "Gordon",
"Position": "CB",
"Age": 26,
"Overall": 84,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 6,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0008",
"First Name": "Colston",
"Last Name": "Loveland",
"Position": "TE",
"Age": 22,
"Overall": 84,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 84,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0009",
"First Name": "Rome",
"Last Name": "Odunze",
"Position": "WR",
"Age": 24,
"Overall": 83,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 15,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0011",
"First Name": "Montez",
"Last Name": "Sweat",
"Position": "LE",
"Age": 29,
"Overall": 82,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 98,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0018",
"First Name": "Cairo",
"Last Name": "Santos",
"Position": "K",
"Age": 34,
"Overall": 78,
"TeamIndex": 0,
"Team": "CHI",
"Status": "Signed",
"Jersey": 8,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0025",
"First Name": "Tyler",
"Last Name": "Davis",
"Position": "DT",
"Age": 25,
"Overall": 74,
"TeamIndex": 0,
"Team": "CHI",
"Status": "PracticeSquad",
"Jersey": 90,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0060",
"First Name": "Ja'Marr",
"Last Name": "Chase",
"Position": "WR",
"Age": 26,
"Overall": 99,
"TeamIndex": 1,
"Team": "CIN",
"Status": "Signed",
"Jersey": 1,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0061",
"First Name": "Joe",
"Last Name": "Burrow",
"Position": "QB",
"Age": 29,
"Overall": 97,
"TeamIndex": 1,
"Team": "CIN",
"Status": "Signed",
"Jersey": 9,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0062",
"First Name": "Dexter",
"Last Name": "Lawrence II",
"Position": "DT",
"Age": 28,
"Overall": 93,
"TeamIndex": 1,
"Team": "CIN",
"Status": "Signed",
"Jersey": 97,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0064",
"First Name": "Tee",
"Last Name": "Higgins",
"Position": "WR",
"Age": 27,
"Overall": 87,
"TeamIndex": 1,
"Team": "CIN",
"Status": "Signed",
"Jersey": 5,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0066",
"First Name": "Chase",
"Last Name": "Brown",
"Position": "HB",
"Age": 26,
"Overall": 82,
"TeamIndex": 1,
"Team": "CIN",
"Status": "Signed",
"Jersey": 30,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
},
{
"PlayerID": "P0067",
"First Name": "Evan",
"Last Name": "McPherson",
"Position": "K",
"Age": 27,
"Overall": 81,
"TeamIndex": 1,
"Team": "CIN",
"Status": "Signed",
"Jersey": 2,
"Height (in)": "",
"Cap Salary (raw)": "",
"Injury Status": "Uninjured",
"Injury Type": "",
"Injury Severity": ""
}
] as unknown as Player[];
export const sampleGames = [
{
"GameID": "SAMPLE1",
"Season": 1,
"Week": 1,
"Stage": "Regular",
"Home": "CHI",
"Away": "DET",
"Home Score": 27,
"Away Score": 24,
"Home Coach": "Wes",
"Away Coach": "CPU",
"Winner": "CHI",
"Margin": 3,
"1v1?": ""
},
{
"GameID": "SAMPLE2",
"Season": 1,
"Week": 1,
"Stage": "Regular",
"Home": "CIN",
"Away": "PIT",
"Home Score": 17,
"Away Score": 20,
"Home Coach": "Christian",
"Away Coach": "CPU",
"Winner": "PIT",
"Margin": 3,
"1v1?": ""
},
{
"GameID": "SAMPLE3",
"Season": 1,
"Week": 2,
"Stage": "Regular",
"Home": "CIN",
"Away": "CHI",
"Home Score": 31,
"Away Score": 28,
"Home Coach": "Christian",
"Away Coach": "Wes",
"Winner": "CIN",
"Margin": 3,
"1v1?": "Yes"
}
] as unknown as Game[];
export const sampleArticles = [
{
"ArticleID": "SAMPLE-A1",
"Season": 1,
"Week": 2,
"Type": "Recap",
"Subjects": "CIN; CHI; Wes; Christian",
"Headline": "Burrow outduels Williams as Christian takes the first Franchise War meeting",
"Summary": "Sample article. Real stories appear here once the app is connected to the league Sheet and an admin publishes them.",
"Key facts used": "31-28 final",
"Status": "Published",
"Published": "2026-10-04"
}
] as unknown as Article[];
export const sampleTabs: Record<string, Row[]> = { Teams: sampleTeams, Players: samplePlayers, Games: sampleGames, Articles: sampleArticles };
